#ifndef __menu_h__
#define __menu_h__
typedef enum MenuItem
{
	HELP = 0,
	FORWARD_FRAME,
	BACKWARD_FRAME,
	RIGHT_KICK,
	LEFT_KICK,
	HEAD_KICK,
	LEFT_PUNCH,
	QUIT,
	LOOK_AT_WATCH,
	ANIMATION_FPS_DOWN,
	ANIMATION_FPS_UP,
	INTERP,
	DOCALC,
	FOLLOW,
	WIREFRAME,
	TEXTURES,
	PAUSE,
	RELOAD,
	RELOADRESOURCES,
	PRINTTREE,
	LIGHT0,
	LIGHT1,
	LIGHT2,
	ROTATE_OBJECT_X_PLUS,
	ROTATE_OBJECT_X_MINUS,
	ROTATE_OBJECT_Y_PLUS,
	ROTATE_OBJECT_Y_MINUS,
	ROTATE_OBJECT_Z_PLUS,
	ROTATE_OBJECT_Z_MINUS,
	SWITCH_FONTS,
} MenuItem;


void handleOption(int itemID);
void setupMenu(void);
#endif // __menu_h__
